# Generated by Django 5.1 on 2026-02-14 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='eligibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_category',
            field=models.CharField(default='Not Calculated', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
