# Generated by Django 5.1 on 2026-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loan_applied_on_loan_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_amount',
            field=models.FloatField(default=0),
        ),
    ]
