# Generated by Django 5.1 on 2026-02-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_due_date_loan_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.FloatField(default=0),
        ),
    ]
