# Generated by Django 5.1 on 2026-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loan_age_loan_document_loan_income_loan_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
