# Generated by Django 5.1 on 2026-02-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent')], default='CUSTOMER', max_length=20),
        ),
    ]
